const {test}=require('node:test');const assert=require('node:assert/strict');const mongoose=require('mongoose');const {randomUUID}=require('crypto');
test('summary resumes successful segments after timeout without nested retries', {skip:!process.env.TEST_MONGODB_URI,timeout:60000},async t=>{
 const dbName='workdiary_resume_test_'+randomUUID().replaceAll('-','');await mongoose.connect(process.env.TEST_MONGODB_URI,{dbName});t.after(async()=>{assert.equal(mongoose.connection.name,dbName);await mongoose.connection.dropDatabase();await mongoose.disconnect()});
 const User=require('../models/User'),Diary=require('../models/Diary'),Job=require('../models/BackgroundJob'),Summary=require('../models/Summary'),queue=require('../services/jobQueue'),workflow=require('../services/summaryWorkflow');
 const user=await User.create({username:'resume',email:'resume@example.invalid',password:'synthetic'});await Diary.create({user:user._id,content:'合成资料'.repeat(22000),startTime:'2026-08-02T01:00:00Z',endTime:'2026-08-02T02:00:00Z'});
 const job=await workflow.enqueue(user.id,{type:'monthly',anchor:'2026-08-02'});const calls=[];let failed=false;const model={config:{timeout:30000,maxTokens:32000},generateText:async(prompt,options)=>{assert.equal(options.retryTransient,false);assert.equal(options.retryTruncated,true);calls.push(prompt);if(calls.length===2&&!failed){failed=true;const e=new Error('timeout');e.code='ECONNABORTED';throw e;}return prompt.includes('只返回JSON数组')?'[]':'已确认阶段成果';}};
 await queue.runOne('summary',(j,cp)=>workflow.generate(j,cp,{model}));let stored=await Job.findById(job.id);assert.equal(stored.status,'failed');assert.match(stored.error,/30秒/);assert.equal(Object.keys(stored.payload.completedCalls).length,1);assert.equal(await Summary.countDocuments(),0);
 const first=calls[0];await queue.retry(user.id,job.id);await queue.runOne('summary',(j,cp)=>workflow.generate(j,cp,{model}));stored=await Job.findById(job.id);assert.equal(stored.status,'succeeded');assert.equal(calls.filter(x=>x===first).length,1);assert.equal(stored.payload.completedCalls,undefined);assert.equal(await Summary.countDocuments(),1);
});
